name: iCourse Check

on:
  schedule:
    # Every day at 13:00 and 22:00 BTC (UTC + 8)
    - cron: "0 5 * * *"
    - cron: "0 14 * * *"
  workflow_dispatch:

jobs:
  check:
    uses: ./.github/workflows/_pipeline.yml
    with:
      course_ids: ${{ secrets.COURSE_IDS }}
    secrets: inherit
